microstrain_inertial_driver:
  ros__parameters:
    aux_baudrate: 921600
    aux_port: /dev/microstrain_aux
    baudrate: 115200
    gnss1_nmea_gga_data_rate: 1
    gnss1_nmea_talker_id: 1
    imu_data_rate: 200
    nmea_message_config: true
    ntrip_interface_enable: true
    port: /dev/microstrain_main
    rtk_dongle_enable: true
    set_baud: false
